package com.foodrisk.dto;

import io.swagger.v3.oas.annotations.media.Schema;

import java.time.Instant;
import java.util.List;

@Schema(description = "Explanation response grounded strictly in verified findings and authoritative sources")
public record ExplainFindingResponse(
        @Schema(description = "Exact name of the finding explained", example = "INS 551")
        String itemName,

        @Schema(description = "Plain-English, non-medical educational explanation", example = "Silicon dioxide (INS 551) is an anti-caking agent permitted under FSSAI and JECFA standards for powdered foods.")
        String explanation,

        @Schema(description = "Traceable authoritative sources supporting this explanation", example = "[\"FSSAI\", \"JECFA\"]")
        List<String> sourceIds,

        @Schema(description = "Whether the explanation was generated by Gemini or deterministically synthesized on fallback", example = "true")
        boolean aiGenerated,

        @Schema(description = "Timestamp when the explanation was produced")
        Instant explainedAt
) {}
